//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPedAppMixedLearning {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsPedAppMixedLearning.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\froman\fprq2\fcharset204 Times New Roman;}{\f1\fnil\fcharset204 Microsoft Sans Serif;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red29\green29\blue27;}
        ///{\*\generator Riched20 10.0.22621}\viewkind4\uc1 
        ///\pard\widctlpar\li89\sa207\sl240\slmult1\cf1\b\f0\fs28\&apos;d7\&apos;f2\&apos;ee \&apos;f2\&apos;e0\&apos;ea\&apos;ee\&apos;e5 Python?\par
        ///
        ///\pard\widctlpar\fi619\li89\sa207\sl240\slmult1\b0 Python \emdash  \&apos;fd\&apos;f2\&apos;ee \&apos;f8\&apos;e8\&apos;f0\&apos;ee\&apos;ea\&apos;ee \&apos;e8\&apos;f1\&apos;ef\&apos;ee\&apos;eb\&apos;fc\&apos;e7\&apos;f3\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Theory1 {
            get {
                return ResourceManager.GetString("Theory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\froman\fprq2\fcharset204 Times New Roman;}{\f1\fnil\fcharset204 Microsoft Sans Serif;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red29\green29\blue27;}
        ///{\*\generator Riched20 10.0.22621}\viewkind4\uc1 
        ///\pard\widctlpar\fi-10\li99\sa207\sl240\slmult1\cf1\b\f0\fs28 Python \&apos;ea\&apos;e0\&apos;ea \&apos;ea\&apos;e0\&apos;eb\&apos;fc\&apos;ea\&apos;f3\&apos;eb\&apos;ff\&apos;f2\&apos;ee\&apos;f0\par
        ///
        ///\pard\widctlpar\fi360\li89\sa207\sl240\slmult1\b0\&apos;d2\&apos;e5\&apos;ef\&apos;e5\&apos;f0\&apos;fc \&apos;ec\&apos;fb \&apos;ef\&apos;ee\&apos;ea\&apos;e0\&apos;e6\&apos;e5\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Theory2 {
            get {
                return ResourceManager.GetString("Theory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\froman\fprq2\fcharset204 Times New Roman;}{\f1\froman\fprq2\fcharset0 Times New Roman;}{\f2\fnil\fcharset1 Cambria Math;}{\f3\fnil\fcharset204 Microsoft Sans Serif;}{\f4\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red29\green29\blue27;}
        ///{\*\generator Riched20 10.0.22621}{\*\mmathPr\mmathFont2\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\fi-10\li99\sa207\sl240\slmult1\cf1\b\f0\fs28\&apos;d7\&apos;f2\&apos;ee \&apos;f2\&apos;e0\&apos;ea\&apos;ee\&apos;e5 \&apos;ef\&apos;e5\&apos;f0\&apos;e5\&apos;ec\&apos;e5\&apos;ed [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Theory3 {
            get {
                return ResourceManager.GetString("Theory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\froman\fprq2\fcharset204 Times New Roman;}{\f1\fnil\fcharset1 Cambria Math;}{\f2\fnil\fcharset204 Microsoft Sans Serif;}{\f3\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red29\green29\blue27;}
        ///{\*\generator Riched20 10.0.22621}{\*\mmathPr\mmathFont1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\li89\sl360\slmult1\cf1\b\f0\fs28\&apos;c2\&apos;ee\&apos;ef\&apos;f0\&apos;ee\&apos;f1\&apos;fb \&apos;e8 \&apos;ee\&apos;f2\&apos;e2\&apos;e5\&apos;f2\&apos;fb\par
        ///
        ///\pard\widctlpar\fi708\sl360\slmult1\b0\&apos;cf\&apos;f0\&apos;ee\&apos;e [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Theory4 {
            get {
                return ResourceManager.GetString("Theory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049{\fonttbl{\f0\froman\fprq2\fcharset204 Times New Roman;}{\f1\fnil\fcharset1 Cambria Math;}{\f2\froman\fprq2\fcharset0 Times New Roman;}{\f3\fnil\fcharset204 Microsoft Sans Serif;}{\f4\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red29\green29\blue27;}
        ///{\*\generator Riched20 10.0.22621}{\*\mmathPr\mmathFont1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\fi-10\li99\sl360\slmult1\cf1\b\f0\fs28\&apos;d1\&apos;ee\&apos;e7\&apos;e4\&apos;e0\&apos;ed\&apos;e8\&apos;e5 \&apos;f6\&apos;e8\&apos;ea\&apos;eb\&apos;ee\&apos;e2 \&apos;f1 \&apos;ef\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Theory5 {
            get {
                return ResourceManager.GetString("Theory5", resourceCulture);
            }
        }
    }
}
